stages:
  - build
  - buildMPI
  - test

.src_except_template: &src_except_definition
  except:
    changes:
      - .gitignore
      - CITATION
      - README.md
      - doc/*

.BUILD_template: &build_definition
  stage: build
  <<: *src_except_definition
  script:
    - apt-get update && apt-get install -y libhdf5-dev
    - cmake -E make_directory build
    - cd build
    - cmake ..
    - make MARQOV

.BUILDMPI_template: &buildMPI_definition
  stage: buildMPI
  <<: *src_except_definition
  script:
    - apt-get update && apt-get install -y libhdf5-dev libopenmpi-dev
    - cmake -E make_directory build
    - cd build
    - cmake ..
    - make mpiMARQOV

.TEST_template: &test_definition
  stage: test
  <<: *src_except_definition
  script:
    - cmake -E make_directory build
    - cd build
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE ..
    - cmake --build . --target all --config Release
    - ctest -O log.txt
    - cat log.txt | grep "tests passed" | cut -d " " -f 1

MARQOV_Ubuntu_bionic:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/ubuntu:bionic-beaver-gfortran-lapack
    stage: build
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y g++ cmake libhdf5-dev
      - cmake -E make_directory build
      - cd build
      - cmake ..
      - make MARQOV

MARQOV_Stretch:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gxx
    <<: *build_definition

MARQOV_Buster:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gxx
    <<: *build_definition

mpiMARQOV_Ubuntu_bionic:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/ubuntu:bionic-beaver-gfortran-lapack
    stage: build
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y g++ cmake libhdf5-dev libopenmpi-dev
      - cmake -E make_directory build
      - cd build
      - cmake ..
      - make mpiMARQOV

mpiMARQOV_Stretch:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gxx
    <<: *buildMPI_definition

mpiMARQOV_Buster:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gxx
    <<: *buildMPI_definition

marqov_Buster_clang:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-clang
    stage: build
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y libhdf5-dev
      - cmake -E make_directory build
      - cd build
      - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_COMPILER=clang++ ..
      - make MARQOV VERBOSE=1

marqov_Buster_pgi:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-pgi1910-cmake
    stage: build
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y libhdf5-dev
      - cmake -E make_directory build
      - cd build
      - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_COMPILER="/opt/pgi/linux86-64/2019/bin/pgc++" ..
      - make MARQOV VERBOSE=1

marqov_create_doc:
  image: aergus/latex
  stage: build
  only:
    changes:
      - doc/*.tex
      - doc/*.bib
      - doc/figures/*
      - doc/files/*
#  artifacts:
#    paths:
#      - doc/main.pdf
  script:
    - cd doc
#    - latexmk -pdf main.tex
