stages:
  - pretest
  - pretest_threaded
  - build
  - buildMPI
  - test
  - docs
  - SWIG

.src_except_template: &src_except_definition
  except:
    changes:
      - .gitignore
      - CITATION
      - README.md
      - doc/*

.BUILD_template: &build_definition
  stage: build
  <<: *src_except_definition
  script:
    - apt-get update && apt-get install -y libhdf5-dev
    - cmake -E make_directory build
    - cd build
    - cmake ..
    - make MARQOVdemo

.BUILDMPI_template: &buildMPI_definition
  stage: buildMPI
  <<: *src_except_definition
  script:
    - apt-get update && apt-get install -y libhdf5-dev libopenmpi-dev
    - cmake -E make_directory build
    - cd build
    - cmake ..
    - make mpiMARQOVdemo

.TEST_template: &test_definition
  stage: test
  <<: *src_except_definition
  script:
    - apt-get update && apt-get install -y cmake libhdf5-dev libeigen3-dev
    - cmake -E make_directory build
    - cd build
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE ..
    - cmake --build . --target all --config Release
    - ctest -O log.txt
    - cat log.txt | grep "tests passed" | cut -d " " -f 1

MARQOV_Simple_Test:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gxx
    stage: pretest
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y cmake libhdf5-dev
      - cmake -E make_directory build
      - cd build
      - cmake ..
      - make mysimpleising

MARQOV_Simple_Threaded_Test:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gxx
    stage: pretest_threaded
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y cmake libhdf5-dev
      - cmake -E make_directory build
      - cd build
      - cmake ..
      - make mysimpleheisenbergthreaded

MARQOV_Ubuntu_bionic:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/ubuntu:bionic-beaver-gfortran-lapack
    stage: build
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y g++ cmake libhdf5-dev
      - cmake -E make_directory build
      - cd build
      - cmake ..
      - make MARQOVdemo

MARQOV_Stretch:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gxx
    <<: *build_definition

MARQOV_Buster:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gxx
    <<: *build_definition

MARQOV_Bullseye:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gxx
    <<: *build_definition

mpiMARQOV_Ubuntu_bionic:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/ubuntu:bionic-beaver-gfortran-lapack
    stage: buildMPI
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y g++ cmake libhdf5-dev libopenmpi-dev
      - cmake -E make_directory build
      - cd build
      - cmake ..
      - make mpiMARQOVdemo

mpiMARQOV_Stretch:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gxx
    <<: *buildMPI_definition

mpiMARQOV_Buster:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gxx
    <<: *buildMPI_definition

marqov_Buster_clang:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-clang
    stage: build
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y libhdf5-dev
      - cmake -E make_directory build
      - cd build
      - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_COMPILER=clang++ ..
      - make MARQOVdemo VERBOSE=1

marqov_Bullseye_clang:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-clang
    stage: build
    <<: *src_except_definition
    script:
      - cmake -E make_directory build
      - cd build
      - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_COMPILER=clang++ ..
      - make MARQOVdemo VERBOSE=1

marqov_Buster_pgi:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-pgi1910-cmake
    stage: build
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y libhdf5-dev
      - cmake -E make_directory build
      - cd build
      - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_COMPILER="/opt/pgi/linux86-64/2019/bin/pgc++" ..
      - make CXX_FLAGS="-O" MARQOVdemo VERBOSE=1

MARQOVtest_Stretch:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gxx
    <<: *test_definition

MARQOVtest_Buster:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gxx
    <<: *test_definition

marqovtest_Bullseye_clang:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-clang
    stage: test
    <<: *src_except_definition
    script:
      - echo "deb http://deb.debian.org/debian bullseye-backports main" >> /etc/apt/sources.list
      - apt-get update && apt-get install -y libhdf5-dev libeigen3-dev
      - apt-get install -y -t bullseye-backports cmake
      - cmake -E make_directory build
      - cd build
      - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_COMPILER=clang++ ..
      - cmake --build . --target all --config Release
      - ctest --version
      - ctest -O log.txt --output-junit marqov-junit.xml
      - cat log.txt | grep "tests passed" | cut -d " " -f 1
    artifacts:
      when: always
      reports:
        junit: ./build/marqov-junit.xml

marqovtest_Buster_pgi:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-pgi-21-03
    stage: test
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y libhdf5-dev libeigen3-dev
      - cmake -E make_directory build
      - cd build
      - cmake -E env CXX_FLAGS="-O -DEIGEN_DONT_VECTORIZE" cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_COMPILER="pgc++" ..
      - cmake --build . --target all --config Release
      - ctest -O log.txt
      - cat log.txt | grep "tests passed" | cut -d " " -f 1

marqov_Bullseye-PGI-21-03:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-pgi-21-03
    stage: build
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y libhdf5-dev cmake
      - cmake -E make_directory build
      - cd build
      - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_COMPILER="pgc++" ..
      - make MARQOVdemo VERBOSE=1

marqov_Bullseye-Intel-21:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-intel-oneapi-icpc
    stage: build
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y libhdf5-dev cmake
      - . /opt/intel/oneapi/setvars.sh
      - cmake -E make_directory build
      - cd build
      - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_COMPILER="icpc" ..
      - make MARQOVdemo VERBOSE=1

marqov_Bullseye_doxygen:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-clang
    stage: build
    script:
      - apt-get update && apt-get install -y doxygen graphviz pdf2svg plantuml
      - cd doc
      - cmake -E make_directory doxygen
      - doxygen Doxyfile-marqov.cfg

marqov_Bullseye_breathe:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-clang
    stage: docs
    needs: ["marqov_Bullseye_doxygen"]
    artifacts: 
      paths:
        - doc/*
    script:
      - apt-get update && apt-get install -y doxygen graphviz pdf2svg python3-breathe python3-sphinx python3-sphinx-rtd-theme python3-sphinxcontrib.plantuml plantuml
      - cd doc/
      - doxygen Doxyfile-marqov-breathe.cfg
      - make html

marqov_sphinx_docs:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
    stage: docs
    needs: ["marqov_Bullseye_doxygen"]
    artifacts: 
      paths:
        - doc/*
    script:
      - apt-get update && apt-get install -y doxygen graphviz pdf2svg python3-breathe python3-sphinx python3-sphinx-rtd-theme git python3-numpy python3-colorama python3-h5py python3-matplotlib python3-sphinxcontrib.plantuml plantuml
      - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.physik.uni-wuerzburg.de/marqov/pymarqov.git
      - ./scripts/compilefulldocs.sh

marqov_Bullseye_SWIG_python:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
    stage: SWIG
    needs: ["MARQOV_Simple_Test"]
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y g++ swig
      - cmake -E make_directory build
      - cd build
      - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE ..
      - make pyShowcase VERBOSE=1

marqov_Bullseye_SWIG_optionals:
    image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
    stage: SWIG
    needs: ["MARQOV_Simple_Test"]
    allow_failure: true
    <<: *src_except_definition
    script:
      - apt-get update && apt-get install -y g++ swig lua5.4-dev default-jdk r-base-dev ocaml-4.11.1
      - cmake -E make_directory build
      - cd build
      - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE ..
      - make pyShowcase JNIShowcase LuaShowcase RShowcase ocamlShowcase VERBOSE=1
